// (C) 2020 GoodData Corporation

// (C) 2007-2020 GoodData Corporatio
export const countriesData = [
    {
        ADMIN: "Aruba",
        ISO_A3: "ABW",
        ISO_A2: "AW",
        case: 4553,
    },
    {
        ADMIN: "Afghanistan",
        ISO_A3: "AFG",
        ISO_A2: "AF",
        case: 41935,
    },
    {
        ADMIN: "Angola",
        ISO_A3: "AGO",
        ISO_A2: "AO",
        case: 11813,
    },
    {
        ADMIN: "Anguilla",
        ISO_A3: "AIA",
        ISO_A2: "AI",
        case: 3,
    },
    {
        ADMIN: "Albania",
        ISO_A3: "ALB",
        ISO_A2: "AL",
        case: 22300,
    },
    {
        ADMIN: "Aland",
        ISO_A3: "ALA",
        ISO_A2: "AX",
        case: 0,
    },
    {
        ADMIN: "Andorra",
        ISO_A3: "AND",
        ISO_A2: "AD",
        case: 5045,
    },
    {
        ADMIN: "United Arab Emirates",
        ISO_A3: "ARE",
        ISO_A2: "AE",
        case: 138599,
    },
    {
        ADMIN: "Argentina",
        ISO_A3: "ARG",
        ISO_A2: "AR",
        case: 1205928,
    },
    {
        ADMIN: "Armenia",
        ISO_A3: "ARM",
        ISO_A2: "AM",
        case: 99563,
    },
    {
        ADMIN: "American Samoa",
        ISO_A3: "ASM",
        ISO_A2: "AS",
        case: 0,
    },
    {
        ADMIN: "Antarctica",
        ISO_A3: "ATA",
        ISO_A2: "AQ",
        case: 0,
    },
    {
        ADMIN: "Ashmore and Cartier Islands",
        ISO_A3: "-99",
        ISO_A2: "AQ",
        case: 0,
    },
    {
        ADMIN: "French Southern and Antarctic Lands",
        ISO_A3: "ATF",
        ISO_A2: "TF",
        case: 0,
    },
    {
        ADMIN: "Antigua and Barbuda",
        ISO_A3: "ATG",
        ISO_A2: "AG",
        case: 130,
    },
    {
        ADMIN: "Australia",
        ISO_A3: "AUS",
        ISO_A2: "AU",
        case: 27634,
    },
    {
        ADMIN: "Austria",
        ISO_A3: "AUT",
        ISO_A2: "AT",
        case: 125099,
    },
    {
        ADMIN: "Azerbaijan",
        ISO_A3: "AZE",
        ISO_A2: "AZ",
        case: 59509,
    },
    {
        ADMIN: "Burundi",
        ISO_A3: "BDI",
        ISO_A2: "BI",
        case: 606,
    },
    {
        ADMIN: "Belgium",
        ISO_A3: "BEL",
        ISO_A2: "BE",
        case: 468213,
    },
    {
        ADMIN: "Benin",
        ISO_A3: "BEN",
        ISO_A2: "BJ",
        case: 2745,
    },
    {
        ADMIN: "Burkina Faso",
        ISO_A3: "BFA",
        ISO_A2: "BF",
        case: 2539,
    },
    {
        ADMIN: "Bangladesh",
        ISO_A3: "BGD",
        ISO_A2: "BD",
        case: 416006,
    },
    {
        ADMIN: "Bulgaria",
        ISO_A3: "BGR",
        ISO_A2: "BG",
        case: 64591,
    },
    {
        ADMIN: "Bahrain",
        ISO_A3: "BHR",
        ISO_A2: "BH",
        case: 82624,
    },
    {
        ADMIN: "The Bahamas",
        ISO_A3: "BHS",
        ISO_A2: "BS",
        case: 6843,
    },
    {
        ADMIN: "Bosnia and Herzegovina",
        ISO_A3: "BIH",
        ISO_A2: "BA",
        case: 55598,
    },
    {
        ADMIN: "Bajo Nuevo Bank (Petrel Is.)",
        ISO_A3: "-99",
        ISO_A2: "UM",
        case: 0,
    },
    {
        ADMIN: "Saint Barthelemy",
        ISO_A3: "BLM",
        ISO_A2: "BL",
        case: 0,
    },
    {
        ADMIN: "Belarus",
        ISO_A3: "BLR",
        ISO_A2: "BY",
        case: 103295,
    },
    {
        ADMIN: "Belize",
        ISO_A3: "BLZ",
        ISO_A2: "BZ",
        case: 3905,
    },
    {
        ADMIN: "Bermuda",
        ISO_A3: "BMU",
        ISO_A2: "BM",
        case: 206,
    },
    {
        ADMIN: "Bolivia",
        ISO_A3: "BOL",
        ISO_A2: "BO",
        case: 142062,
    },
    {
        ADMIN: "Brazil",
        ISO_A3: "BRA",
        ISO_A2: "BR",
        case: 5590941,
    },
    {
        ADMIN: "Barbados",
        ISO_A3: "BRB",
        ISO_A2: "BB",
        case: 239,
    },
    {
        ADMIN: "Brunei",
        ISO_A3: "BRN",
        ISO_A2: "BN",
        case: 148,
    },
    {
        ADMIN: "Bhutan",
        ISO_A3: "BTN",
        ISO_A2: "BT",
        case: 358,
    },
    {
        ADMIN: "Botswana",
        ISO_A3: "BWA",
        ISO_A2: "BW",
        case: 6642,
    },
    {
        ADMIN: "Central African Republic",
        ISO_A3: "CAF",
        ISO_A2: "CF",
        case: 0,
    },
    {
        ADMIN: "Canada",
        ISO_A3: "CAN",
        ISO_A2: "CA",
        case: 247703,
    },
    {
        ADMIN: "Switzerland",
        ISO_A3: "CHE",
        ISO_A2: "CH",
        case: 192376,
    },
    {
        ADMIN: "Chile",
        ISO_A3: "CHL",
        ISO_A2: "CL",
        case: 515042,
    },
    {
        ADMIN: "China",
        ISO_A3: "CHN",
        ISO_A2: "CN",
        case: 86115,
    },
    {
        ADMIN: "Ivory Coast",
        ISO_A3: "CIV",
        ISO_A2: "CI",
        case: 20778,
    },
    {
        ADMIN: "Clipperton Island",
        ISO_A3: "-99",
        ISO_A2: "-",
        case: 0,
    },
    {
        ADMIN: "Cameroon",
        ISO_A3: "CMR",
        ISO_A2: "CM",
        case: 22103,
    },
    {
        ADMIN: "Cyprus No Mans Area",
        ISO_A3: "-99",
        ISO_A2: "-",
        case: 5100,
    },
    {
        ADMIN: "Democratic Republic of the Congo",
        ISO_A3: "COD",
        ISO_A2: "CD",
        case: 5348,
    },
    {
        ADMIN: "Republic of Congo",
        ISO_A3: "COG",
        ISO_A2: "CG",
        case: 5348,
    },
    {
        ADMIN: "Cook Islands",
        ISO_A3: "COK",
        ISO_A2: "CK",
        case: 0,
    },
    {
        ADMIN: "Colombia",
        ISO_A3: "COL",
        ISO_A2: "CO",
        case: 1108084,
    },
    {
        ADMIN: "Comoros",
        ISO_A3: "COM",
        ISO_A2: "KM",
        case: 554,
    },
    {
        ADMIN: "Cape Verde",
        ISO_A3: "CPV",
        ISO_A2: "CV",
        case: 0,
    },
    {
        ADMIN: "Costa Rica",
        ISO_A3: "CRI",
        ISO_A2: "CR",
        case: 113261,
    },
    {
        ADMIN: "Coral Sea Islands",
        ISO_A3: "-99",
        ISO_A2: "-",
        case: 0,
    },
    {
        ADMIN: "Cuba",
        ISO_A3: "CUB",
        ISO_A2: "CU",
        case: 7144,
    },
    {
        ADMIN: "Curaçao",
        ISO_A3: "CUW",
        ISO_A2: "CW",
        case: 1021,
    },
    {
        ADMIN: "Cayman Islands",
        ISO_A3: "CYM",
        ISO_A2: "KY",
        case: 242,
    },
    {
        ADMIN: "Northern Cyprus",
        ISO_A3: "-99",
        ISO_A2: "-",
        case: 5100,
    },
    {
        ADMIN: "Cyprus",
        ISO_A3: "CYP",
        ISO_A2: "CY",
        case: 5100,
    },
    {
        ADMIN: "Czech Republic",
        ISO_A3: "CZE",
        ISO_A2: "CZ",
        case: 378716,
    },
    {
        ADMIN: "Germany",
        ISO_A3: "DEU",
        ISO_A2: "DE",
        case: 597453,
    },
    {
        ADMIN: "Djibouti",
        ISO_A3: "DJI",
        ISO_A2: "DJ",
        case: 5580,
    },
    {
        ADMIN: "Dominica",
        ISO_A3: "DMA",
        ISO_A2: "DM",
        case: 50,
    },
    {
        ADMIN: "Denmark",
        ISO_A3: "DNK",
        ISO_A2: "DK",
        case: 50530,
    },
    {
        ADMIN: "Dominican Republic",
        ISO_A3: "DOM",
        ISO_A2: "DO",
        case: 128278,
    },
    {
        ADMIN: "Algeria",
        ISO_A3: "DZA",
        ISO_A2: "DZ",
        case: 59527,
    },
    {
        ADMIN: "Ecuador",
        ISO_A3: "ECU",
        ISO_A2: "EC",
        case: 171433,
    },
    {
        ADMIN: "Egypt",
        ISO_A3: "EGY",
        ISO_A2: "EG",
        case: 108329,
    },
    {
        ADMIN: "Eritrea",
        ISO_A3: "ERI",
        ISO_A2: "ER",
        case: 480,
    },
    {
        ADMIN: "Dhekelia Sovereign Base Area",
        ISO_A3: "-99",
        ISO_A2: "-",
        case: 0,
    },
    {
        ADMIN: "Spain",
        ISO_A3: "ESP",
        ISO_A2: "ES",
        case: 1356798,
    },
    {
        ADMIN: "Estonia",
        ISO_A3: "EST",
        ISO_A2: "EE",
        case: 5464,
    },
    {
        ADMIN: "Ethiopia",
        ISO_A3: "ETH",
        ISO_A2: "ET",
        case: 97881,
    },
    {
        ADMIN: "Finland",
        ISO_A3: "FIN",
        ISO_A2: "FI",
        case: 17119,
    },
    {
        ADMIN: "Fiji",
        ISO_A3: "FJI",
        ISO_A2: "FJ",
        case: 34,
    },
    {
        ADMIN: "Falkland Islands",
        ISO_A3: "FLK",
        ISO_A2: "FK",
        case: 13,
    },
    {
        ADMIN: "France",
        ISO_A3: "FRA",
        ISO_A2: "FR",
        case: 1543321,
    },
    {
        ADMIN: "Faroe Islands",
        ISO_A3: "FRO",
        ISO_A2: "FO",
        case: 0,
    },
    {
        ADMIN: "Federated States of Micronesia",
        ISO_A3: "FSM",
        ISO_A2: "FM",
        case: 0,
    },
    {
        ADMIN: "Gabon",
        ISO_A3: "GAB",
        ISO_A2: "GA",
        case: 9005,
    },
    {
        ADMIN: "United Kingdom",
        ISO_A3: "GBR",
        ISO_A2: "GB",
        case: 1099059,
    },
    {
        ADMIN: "Georgia",
        ISO_A3: "GEO",
        ISO_A2: "GE",
        case: 49218,
    },
    {
        ADMIN: "Guernsey",
        ISO_A3: "GGY",
        ISO_A2: "GG",
        case: 0,
    },
    {
        ADMIN: "Ghana",
        ISO_A3: "GHA",
        ISO_A2: "GH",
        case: 48643,
    },
    {
        ADMIN: "Gibraltar",
        ISO_A3: "GIB",
        ISO_A2: "GI",
        case: 754,
    },
    {
        ADMIN: "Guinea",
        ISO_A3: "GIN",
        ISO_A2: "GN",
        case: 12331,
    },
    {
        ADMIN: "Gambia",
        ISO_A3: "GMB",
        ISO_A2: "GM",
        case: 3680,
    },
    {
        ADMIN: "Guinea Bissau",
        ISO_A3: "GNB",
        ISO_A2: "GW",
        case: 2414,
    },
    {
        ADMIN: "Equatorial Guinea",
        ISO_A3: "GNQ",
        ISO_A2: "GQ",
        case: 5092,
    },
    {
        ADMIN: "Greece",
        ISO_A3: "GRC",
        ISO_A2: "GR",
        case: 46892,
    },
    {
        ADMIN: "Grenada",
        ISO_A3: "GRD",
        ISO_A2: "GD",
        case: 30,
    },
    {
        ADMIN: "Greenland",
        ISO_A3: "GRL",
        ISO_A2: "GL",
        case: 17,
    },
    {
        ADMIN: "Guatemala",
        ISO_A3: "GTM",
        ISO_A2: "GT",
        case: 109147,
    },
    {
        ADMIN: "Guam",
        ISO_A3: "GUM",
        ISO_A2: "GU",
        case: 0,
    },
    {
        ADMIN: "Guyana",
        ISO_A3: "GUY",
        ISO_A2: "GY",
        case: 4324,
    },
    {
        ADMIN: "Hong Kong S.A.R.",
        ISO_A3: "HKG",
        ISO_A2: "HK",
        case: 5356,
    },
    {
        ADMIN: "Heard Island and McDonald Islands",
        ISO_A3: "HMD",
        ISO_A2: "HM",
        case: 0,
    },
    {
        ADMIN: "Honduras",
        ISO_A3: "HND",
        ISO_A2: "HN",
        case: 99124,
    },
    {
        ADMIN: "Croatia",
        ISO_A3: "HRV",
        ISO_A2: "HR",
        case: 59415,
    },
    {
        ADMIN: "Haiti",
        ISO_A3: "HTI",
        ISO_A2: "HT",
        case: 9100,
    },
    {
        ADMIN: "Hungary",
        ISO_A3: "HUN",
        ISO_A2: "HU",
        case: 94916,
    },
    {
        ADMIN: "Indonesia",
        ISO_A3: "IDN",
        ISO_A2: "ID",
        case: 425796,
    },
    {
        ADMIN: "Isle of Man",
        ISO_A3: "IMN",
        ISO_A2: "IM",
        case: 357,
    },
    {
        ADMIN: "India",
        ISO_A3: "IND",
        ISO_A2: "IN",
        case: 8380734,
    },
    {
        ADMIN: "Indian Ocean Territories",
        ISO_A3: "-99",
        ISO_A2: "-",
        case: 0,
    },
    {
        ADMIN: "British Indian Ocean Territory",
        ISO_A3: "IOT",
        ISO_A2: "IO",
        case: 0,
    },
    {
        ADMIN: "Ireland",
        ISO_A3: "IRL",
        ISO_A2: "IE",
        case: 63483,
    },
    {
        ADMIN: "Iran",
        ISO_A3: "IRN",
        ISO_A2: "IR",
        case: 654936,
    },
    {
        ADMIN: "Iraq",
        ISO_A3: "IRQ",
        ISO_A2: "IQ",
        case: 489571,
    },
    {
        ADMIN: "Iceland",
        ISO_A3: "ISL",
        ISO_A2: "IS",
        case: 5017,
    },
    {
        ADMIN: "Israel",
        ISO_A3: "ISR",
        ISO_A2: "IL",
        case: 317668,
    },
    {
        ADMIN: "Italy",
        ISO_A3: "ITA",
        ISO_A2: "IT",
        case: 790377,
    },
    {
        ADMIN: "Jamaica",
        ISO_A3: "JAM",
        ISO_A2: "JM",
        case: 9373,
    },
    {
        ADMIN: "Jersey",
        ISO_A3: "JEY",
        ISO_A2: "JE",
        case: 0,
    },
    {
        ADMIN: "Jordan",
        ISO_A3: "JOR",
        ISO_A2: "JO",
        case: 91234,
    },
    {
        ADMIN: "Japan",
        ISO_A3: "JPN",
        ISO_A2: "JP",
        case: 102900,
    },
    {
        ADMIN: "Baykonur Cosmodrome",
        ISO_A3: "-99",
        ISO_A2: "-",
        case: 0,
    },
    {
        ADMIN: "Siachen Glacier",
        ISO_A3: "-99",
        ISO_A2: "-",
        case: 0,
    },
    {
        ADMIN: "Kazakhstan",
        ISO_A3: "KAZ",
        ISO_A2: "KZ",
        case: 114235,
    },
    {
        ADMIN: "Kenya",
        ISO_A3: "KEN",
        ISO_A2: "KE",
        case: 58587,
    },
    {
        ADMIN: "Kyrgyzstan",
        ISO_A3: "KGZ",
        ISO_A2: "KG",
        case: 61309,
    },
    {
        ADMIN: "Cambodia",
        ISO_A3: "KHM",
        ISO_A2: "KH",
        case: 292,
    },
    {
        ADMIN: "Kiribati",
        ISO_A3: "KIR",
        ISO_A2: "KI",
        case: 0,
    },
    {
        ADMIN: "Saint Kitts and Nevis",
        ISO_A3: "KNA",
        ISO_A2: "KN",
        case: 19,
    },
    {
        ADMIN: "South Korea",
        ISO_A3: "KOR",
        ISO_A2: "KR",
        case: 0,
    },
    {
        ADMIN: "Kosovo",
        ISO_A3: "-99",
        ISO_A2: "-",
        case: 0,
    },
    {
        ADMIN: "Kuwait",
        ISO_A3: "KWT",
        ISO_A2: "KW",
        case: 129638,
    },
    {
        ADMIN: "Laos",
        ISO_A3: "LAO",
        ISO_A2: "LA",
        case: 24,
    },
    {
        ADMIN: "Lebanon",
        ISO_A3: "LBN",
        ISO_A2: "LB",
        case: 87097,
    },
    {
        ADMIN: "Liberia",
        ISO_A3: "LBR",
        ISO_A2: "LR",
        case: 1438,
    },
    {
        ADMIN: "Libya",
        ISO_A3: "LBY",
        ISO_A2: "LY",
        case: 65440,
    },
    {
        ADMIN: "Saint Lucia",
        ISO_A3: "LCA",
        ISO_A2: "LC",
        case: 105,
    },
    {
        ADMIN: "Liechtenstein",
        ISO_A3: "LIE",
        ISO_A2: "LI",
        case: 659,
    },
    {
        ADMIN: "Sri Lanka",
        ISO_A3: "LKA",
        ISO_A2: "LK",
        case: 12400,
    },
    {
        ADMIN: "Lesotho",
        ISO_A3: "LSO",
        ISO_A2: "LS",
        case: 1963,
    },
    {
        ADMIN: "Lithuania",
        ISO_A3: "LTU",
        ISO_A2: "LT",
        case: 19091,
    },
    {
        ADMIN: "Luxembourg",
        ISO_A3: "LUX",
        ISO_A2: "LU",
        case: 20344,
    },
    {
        ADMIN: "Latvia",
        ISO_A3: "LVA",
        ISO_A2: "LV",
        case: 7119,
    },
    {
        ADMIN: "Macao S.A.R",
        ISO_A3: "MAC",
        ISO_A2: "MO",
        case: 46,
    },
    {
        ADMIN: "Saint Martin",
        ISO_A3: "MAF",
        ISO_A2: "MF",
        case: 604,
    },
    {
        ADMIN: "Morocco",
        ISO_A3: "MAR",
        ISO_A2: "MA",
        case: 235310,
    },
    {
        ADMIN: "Monaco",
        ISO_A3: "MCO",
        ISO_A2: "MC",
        case: 412,
    },
    {
        ADMIN: "Moldova",
        ISO_A3: "MDA",
        ISO_A2: "MD",
        case: 79566,
    },
    {
        ADMIN: "Madagascar",
        ISO_A3: "MDG",
        ISO_A2: "MG",
        case: 17111,
    },
    {
        ADMIN: "Maldives",
        ISO_A3: "MDV",
        ISO_A2: "MV",
        case: 11822,
    },
    {
        ADMIN: "Mexico",
        ISO_A3: "MEX",
        ISO_A2: "MX",
        case: 943630,
    },
    {
        ADMIN: "Marshall Islands",
        ISO_A3: "MHL",
        ISO_A2: "MH",
        case: 2,
    },
    {
        ADMIN: "Macedonia",
        ISO_A3: "MKD",
        ISO_A2: "MK",
        case: 35097,
    },
    {
        ADMIN: "Mali",
        ISO_A3: "MLI",
        ISO_A2: "ML",
        case: 3609,
    },
    {
        ADMIN: "Malta",
        ISO_A3: "MLT",
        ISO_A2: "MT",
        case: 6764,
    },
    {
        ADMIN: "Myanmar",
        ISO_A3: "MMR",
        ISO_A2: "MM",
        case: 57935,
    },
    {
        ADMIN: "Montenegro",
        ISO_A3: "MNE",
        ISO_A2: "ME",
        case: 20851,
    },
    {
        ADMIN: "Mongolia",
        ISO_A3: "MNG",
        ISO_A2: "MN",
        case: 353,
    },
    {
        ADMIN: "Northern Mariana Islands",
        ISO_A3: "MNP",
        ISO_A2: "MP",
        case: 0,
    },
    {
        ADMIN: "Mozambique",
        ISO_A3: "MOZ",
        ISO_A2: "MZ",
        case: 13283,
    },
    {
        ADMIN: "Mauritania",
        ISO_A3: "MRT",
        ISO_A2: "MR",
        case: 7744,
    },
    {
        ADMIN: "Montserrat",
        ISO_A3: "MSR",
        ISO_A2: "MS",
        case: 13,
    },
    {
        ADMIN: "Mauritius",
        ISO_A3: "MUS",
        ISO_A2: "MU",
        case: 452,
    },
    {
        ADMIN: "Malawi",
        ISO_A3: "MWI",
        ISO_A2: "MW",
        case: 5934,
    },
    {
        ADMIN: "Malaysia",
        ISO_A3: "MYS",
        ISO_A2: "MY",
        case: 36434,
    },
    {
        ADMIN: "Namibia",
        ISO_A3: "NAM",
        ISO_A2: "NA",
        case: 13046,
    },
    {
        ADMIN: "New Caledonia",
        ISO_A3: "NCL",
        ISO_A2: "NC",
        case: 28,
    },
    {
        ADMIN: "Niger",
        ISO_A3: "NER",
        ISO_A2: "NE",
        case: 1225,
    },
    {
        ADMIN: "Norfolk Island",
        ISO_A3: "NFK",
        ISO_A2: "NF",
        case: 0,
    },
    {
        ADMIN: "Nigeria",
        ISO_A3: "NGA",
        ISO_A2: "NG",
        case: 63328,
    },
    {
        ADMIN: "Nicaragua",
        ISO_A3: "NIC",
        ISO_A2: "NI",
        case: 5514,
    },
    {
        ADMIN: "Niue",
        ISO_A3: "NIU",
        ISO_A2: "NU",
        case: 0,
    },
    {
        ADMIN: "Netherlands",
        ISO_A3: "NLD",
        ISO_A2: "NL",
        case: 390488,
    },
    {
        ADMIN: "Norway",
        ISO_A3: "NOR",
        ISO_A2: "NO",
        case: 22953,
    },
    {
        ADMIN: "Nepal",
        ISO_A3: "NPL",
        ISO_A2: "NP",
        case: 185974,
    },
    {
        ADMIN: "Nauru",
        ISO_A3: "NRU",
        ISO_A2: "NR",
        case: 0,
    },
    {
        ADMIN: "New Zealand",
        ISO_A3: "NZL",
        ISO_A2: "NZ",
        case: 1973,
    },
    {
        ADMIN: "Oman",
        ISO_A3: "OMN",
        ISO_A2: "OM",
        case: 117167,
    },
    {
        ADMIN: "Pakistan",
        ISO_A3: "PAK",
        ISO_A2: "PK",
        case: 336875,
    },
    {
        ADMIN: "Panama",
        ISO_A3: "PAN",
        ISO_A2: "PA",
        case: 136024,
    },
    {
        ADMIN: "Pitcairn Islands",
        ISO_A3: "PCN",
        ISO_A2: "PN",
        case: 0,
    },
    {
        ADMIN: "Peru",
        ISO_A3: "PER",
        ISO_A2: "PE",
        case: 911787,
    },
    {
        ADMIN: "Spratly Islands",
        ISO_A3: "-99",
        ISO_A2: "-",
        case: 0,
    },
    {
        ADMIN: "Philippines",
        ISO_A3: "PHL",
        ISO_A2: "PH",
        case: 389725,
    },
    {
        ADMIN: "Palau",
        ISO_A3: "PLW",
        ISO_A2: "PW",
        case: 0,
    },
    {
        ADMIN: "Papua New Guinea",
        ISO_A3: "PNG",
        ISO_A2: "PG",
        case: 597,
    },
    {
        ADMIN: "Poland",
        ISO_A3: "POL",
        ISO_A2: "PL",
        case: 466679,
    },
    {
        ADMIN: "Puerto Rico",
        ISO_A3: "PRI",
        ISO_A2: "PR",
        case: 0,
    },
    {
        ADMIN: "North Korea",
        ISO_A3: "PRK",
        ISO_A2: "KP",
        case: 27050,
    },
    {
        ADMIN: "Portugal",
        ISO_A3: "PRT",
        ISO_A2: "PT",
        case: 161350,
    },
    {
        ADMIN: "Paraguay",
        ISO_A3: "PRY",
        ISO_A2: "PY",
        case: 65258,
    },
    {
        ADMIN: "Palestine",
        ISO_A3: "PSE",
        ISO_A2: "PS",
        case: 56672,
    },
    {
        ADMIN: "French Polynesia",
        ISO_A3: "PYF",
        ISO_A2: "PF",
        case: 9287,
    },
    {
        ADMIN: "Qatar",
        ISO_A3: "QAT",
        ISO_A2: "QA",
        case: 133619,
    },
    {
        ADMIN: "Romania",
        ISO_A3: "ROU",
        ISO_A2: "RO",
        case: 276802,
    },
    {
        ADMIN: "Russia",
        ISO_A3: "RUS",
        ISO_A2: "RU",
        case: 1712858,
    },
    {
        ADMIN: "Rwanda",
        ISO_A3: "RWA",
        ISO_A2: "RW",
        case: 5174,
    },
    {
        ADMIN: "Western Sahara",
        ISO_A3: "ESH",
        ISO_A2: "EH",
        case: 10,
    },
    {
        ADMIN: "Saudi Arabia",
        ISO_A3: "SAU",
        ISO_A2: "SA",
        case: 349386,
    },
    {
        ADMIN: "Scarborough Reef",
        ISO_A3: "-99",
        ISO_A2: "-",
        case: 0,
    },
    {
        ADMIN: "Sudan",
        ISO_A3: "SDN",
        ISO_A2: "SD",
        case: 13943,
    },
    {
        ADMIN: "South Sudan",
        ISO_A3: "SSD",
        ISO_A2: "SS",
        case: 2943,
    },
    {
        ADMIN: "Senegal",
        ISO_A3: "SEN",
        ISO_A2: "SN",
        case: 15668,
    },
    {
        ADMIN: "Serranilla Bank",
        ISO_A3: "-99",
        ISO_A2: "-",
        case: 0,
    },
    {
        ADMIN: "Singapore",
        ISO_A3: "SGP",
        ISO_A2: "SG",
        case: 58043,
    },
    {
        ADMIN: "South Georgia and South Sandwich Islands",
        ISO_A3: "SGS",
        ISO_A2: "GS",
        case: 0,
    },
    {
        ADMIN: "Saint Helena",
        ISO_A3: "SHN",
        ISO_A2: "SH",
        case: 0,
    },
    {
        ADMIN: "Solomon Islands",
        ISO_A3: "SLB",
        ISO_A2: "SB",
        case: 13,
    },
    {
        ADMIN: "Sierra Leone",
        ISO_A3: "SLE",
        ISO_A2: "SL",
        case: 2369,
    },
    {
        ADMIN: "El Salvador",
        ISO_A3: "SLV",
        ISO_A2: "SV",
        case: 34782,
    },
    {
        ADMIN: "San Marino",
        ISO_A3: "SMR",
        ISO_A2: "SM",
        case: 994,
    },
    {
        ADMIN: "Somaliland",
        ISO_A3: "-99",
        ISO_A2: "-",
        case: 0,
    },
    {
        ADMIN: "Somalia",
        ISO_A3: "SOM",
        ISO_A2: "SO",
        case: 4229,
    },
    {
        ADMIN: "Saint Pierre and Miquelon",
        ISO_A3: "SPM",
        ISO_A2: "PM",
        case: 16,
    },
    {
        ADMIN: "Republic of Serbia",
        ISO_A3: "SRB",
        ISO_A2: "RS",
        case: 55676,
    },
    {
        ADMIN: "Sao Tome and Principe",
        ISO_A3: "STP",
        ISO_A2: "ST",
        case: 958,
    },
    {
        ADMIN: "Suriname",
        ISO_A3: "SUR",
        ISO_A2: "SR",
        case: 5220,
    },
    {
        ADMIN: "Slovakia",
        ISO_A3: "SVK",
        ISO_A2: "SK",
        case: 68734,
    },
    {
        ADMIN: "Slovenia",
        ISO_A3: "SVN",
        ISO_A2: "SI",
        case: 41094,
    },
    {
        ADMIN: "Sweden",
        ISO_A3: "SWE",
        ISO_A2: "SE",
        case: 141764,
    },
    {
        ADMIN: "Swaziland",
        ISO_A3: "SWZ",
        ISO_A2: "SZ",
        case: 0,
    },
    {
        ADMIN: "Sint Maarten",
        ISO_A3: "SXM",
        ISO_A2: "SX",
        case: 870,
    },
    {
        ADMIN: "Seychelles",
        ISO_A3: "SYC",
        ISO_A2: "SC",
        case: 157,
    },
    {
        ADMIN: "Syria",
        ISO_A3: "SYR",
        ISO_A2: "SY",
        case: 5964,
    },
    {
        ADMIN: "Turks and Caicos Islands",
        ISO_A3: "TCA",
        ISO_A2: "TC",
        case: 705,
    },
    {
        ADMIN: "Chad",
        ISO_A3: "TCD",
        ISO_A2: "TD",
        case: 1517,
    },
    {
        ADMIN: "Togo",
        ISO_A3: "TGO",
        ISO_A2: "TG",
        case: 2406,
    },
    {
        ADMIN: "Thailand",
        ISO_A3: "THA",
        ISO_A2: "TH",
        case: 3810,
    },
    {
        ADMIN: "Tajikistan",
        ISO_A3: "TJK",
        ISO_A2: "TJ",
        case: 11219,
    },
    {
        ADMIN: "Turkmenistan",
        ISO_A3: "TKM",
        ISO_A2: "TM",
        case: 0,
    },
    {
        ADMIN: "East Timor",
        ISO_A3: "TLS",
        ISO_A2: "TL",
        case: 0,
    },
    {
        ADMIN: "Tonga",
        ISO_A3: "TON",
        ISO_A2: "TO",
        case: 0,
    },
    {
        ADMIN: "Trinidad and Tobago",
        ISO_A3: "TTO",
        ISO_A2: "TT",
        case: 5764,
    },
    {
        ADMIN: "Tunisia",
        ISO_A3: "TUN",
        ISO_A2: "TN",
        case: 66334,
    },
    {
        ADMIN: "Turkey",
        ISO_A3: "TUR",
        ISO_A2: "TR",
        case: 386820,
    },
    {
        ADMIN: "Tuvalu",
        ISO_A3: "TUV",
        ISO_A2: "TV",
        case: 0,
    },
    {
        ADMIN: "Taiwan",
        ISO_A3: "TWN",
        ISO_A2: "TW",
        case: 569,
    },
    {
        ADMIN: "United Republic of Tanzania",
        ISO_A3: "TZA",
        ISO_A2: "TZ",
        case: 509,
    },
    {
        ADMIN: "Uganda",
        ISO_A3: "UGA",
        ISO_A2: "UG",
        case: 13568,
    },
    {
        ADMIN: "Ukraine",
        ISO_A3: "UKR",
        ISO_A2: "UA",
        case: 430467,
    },
    {
        ADMIN: "United States Minor Outlying Islands",
        ISO_A3: "UMI",
        ISO_A2: "UM",
        case: 0,
    },
    {
        ADMIN: "Uruguay",
        ISO_A3: "URY",
        ISO_A2: "UY",
        case: 3245,
    },
    {
        ADMIN: "United States of America",
        ISO_A3: "USA",
        ISO_A2: "US",
        case: 9810930,
    },
    {
        ADMIN: "US Naval Base Guantanamo Bay",
        ISO_A3: "-99",
        ISO_A2: "-",
        case: 0,
    },
    {
        ADMIN: "Uzbekistan",
        ISO_A3: "UZB",
        ISO_A2: "UZ",
        case: 68009,
    },
    {
        ADMIN: "Vatican",
        ISO_A3: "VAT",
        ISO_A2: "VA",
        case: 27,
    },
    {
        ADMIN: "Saint Vincent and the Grenadines",
        ISO_A3: "VCT",
        ISO_A2: "VC",
        case: 0,
    },
    {
        ADMIN: "Venezuela",
        ISO_A3: "VEN",
        ISO_A2: "VE",
        case: 93480,
    },
    {
        ADMIN: "British Virgin Islands",
        ISO_A3: "VGB",
        ISO_A2: "VG",
        case: 71,
    },
    {
        ADMIN: "United States Virgin Islands",
        ISO_A3: "VIR",
        ISO_A2: "VI",
        case: 71,
    },
    {
        ADMIN: "Vietnam",
        ISO_A3: "VNM",
        ISO_A2: "VN",
        case: 1207,
    },
    {
        ADMIN: "Vanuatu",
        ISO_A3: "VUT",
        ISO_A2: "VU",
        case: 0,
    },
    {
        ADMIN: "Wallis and Futuna",
        ISO_A3: "WLF",
        ISO_A2: "WF",
        case: 1,
    },
    {
        ADMIN: "Akrotiri Sovereign Base Area",
        ISO_A3: "-99",
        ISO_A2: "-",
        case: 0,
    },
    {
        ADMIN: "Samoa",
        ISO_A3: "WSM",
        ISO_A2: "WS",
        case: 0,
    },
    {
        ADMIN: "Yemen",
        ISO_A3: "YEM",
        ISO_A2: "YE",
        case: 2063,
    },
    {
        ADMIN: "South Africa",
        ISO_A3: "ZAF",
        ISO_A2: "ZA",
        case: 730548,
    },
    {
        ADMIN: "Zambia",
        ISO_A3: "ZMB",
        ISO_A2: "ZM",
        case: 16698,
    },
    {
        ADMIN: "Zimbabwe",
        ISO_A3: "ZWE",
        ISO_A2: "ZW",
        case: 8427,
    },
];
